### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by Rachitidk** [libredirect/browser_extension#1014]
None of instances of intsa is working. Add new one.

**Comment by ManeraKai** [comment]
Instagram is very hard to make a frontend for. There was a project previous to [Proxigram](https://codeberg.org/proxigram/proxigram) (the only instagram frontend in LibRedirect) that got discontinued because of this. See [Discontinuing Bibliogram](https://cadence.moe/blog/2022-09-01-discontinuing-bibliogram).
In LibRedirect, we are just a browser extension that redirects to these frontends. We can't create more instances.
