### ISSUE TITLE
Add redirections for Hackernews

### ISSUE THREAD

**Issue by ghost** [libredirect/browser_extension#239]
Hackernews is a social news network. There are two libre front-ends available for it which would be nice to have:
- https://github.com/algolia/hn-search
- https://github.com/rajatkulkarni95/hckrnws

**Comment by EdwardLangdon** [comment]
It's great to know, But What does it add to Privacy Can you list that ?

**Comment by m77e4t** [comment]
Libredirect (fork of Privacy redirect) is an Privacy enhancing software.
Unless and until the redirection does not offer any privacy benefit I don't think we should offer any redirection.
If not then then Libredirect will have to offer 100's of redirection for no reason.

Hacker news [news.ycombinator.com] itself is not privacy harming in any way.

**Comment by ManeraKai** [comment]
LibRedirect main goal is to redirect to multiple random decentralized privacy friendly instances. I'll treat those two like how I treated Qwant, Mojek, and Startpage, if someone wants them to be redirected, then make a separate extension for them: [Qwant](https://addons.mozilla.org/en-US/firefox/addon/qwantcom-for-firefox/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search), [Mojek](https://addons.mozilla.org/en-US/firefox/addon/mojeek-search/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search), [Startpage](https://addons.mozilla.org/en-US/firefox/addon/startpage-private-search/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)

I think I'll also do the same with old.reddit.com as there's already an [extension](https://addons.mozilla.org/en-US/firefox/addon/old-reddit-redirect/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) with over 32,000 users for it.

I think I'll also remove [pixiv.moe](https://github.com/kokororin/pixiv.moe) as there's only one instance and it's not that privacy friendly. it even now requires a login and you can't browse anything without logging in. ex:
https://pixiv.moe
https://pixiv.moe/illust/96572356

I don't want to bloat the extension. I'll just add those who are privacy friendly or who are the best but not the perfect option for privacy that's available right now.

**Comment by ManeraKai** [comment]
> I think removing Firefox Send would also make sense. Because there rarely is a case where you will get redirected and it adds uneccesary bloat.

Problem with Send is that it's really hard to find and I want to distribute the load between instances. getting redirected is really hard so that's why I added links to the popup. Press on any service/frontend in the popup and you'll get redirected right away to a random instance.

Thinking also of LibreSpeed too as it only has one instance and I'm just redirecting the root path `/` and nothing else useful.

**Comment by vairag22** [comment]
Then Send should be a button like Instance, Settings and Copy Raw.

**Comment by ManeraKai** [comment]
it's already like this. Just go the general settings tab an enable it to be shown. Maybe I should show it by default.
![image](https://user-images.githubusercontent.com/40805353/166669600-87ae3b53-464d-4740-b882-323b90b1476b.png)

**Comment by vairag22** [comment]
Nope. It's a toggle button, not a "button" button like Settings or Copy Raw.

![image](https://user-images.githubusercontent.com/71322586/166669678-b35b9d2d-22d5-4be0-a016-9dab4da4bbd9.png)

**Comment by ManeraKai** [comment]
will just be out of context. It's a Frontend not a function. all the other frontends have the same functionality.

**Comment by vairag22** [comment]
Since Firefox Send has been discontinued it redirects from which website?

**Comment by ManeraKai** [comment]
https://github.com/timvisee/send

**Comment by vairag22** [comment]
Okay I checked _sendTargets.js_.

`const targets = [
    /^https?:\/{2}send.invalid\/$/,
    /^ https ?: \/\/send\.firefox\.com\/$/,
    /^https?:\/{2}sendfiles\.online\/$/
];`

It only redirects from [https://send.invalid]() and [https://sendfiles.online]() not [https://send.firefox.com](https://send.firefox.com).

**Comment by vairag22** [comment]
> will just be out of context. It's a Frontend not a function. all the other frontend buttons have the same functionality.

I understand now. I always tried redirecting from [send.firefox.com]() but that didn't work so I assumed it must be a "button" of some sort (not a toggle).

**Comment by ManeraKai** [comment]
I'll try to add more links for redirecting off of them for Send.

**Comment by vairag22** [comment]
Is this issues still relevant?

**Comment by vairag22** [comment]
Is this issue still relevant?

**Comment by ManeraKai** [comment]
Yes, The only thing I don't like is it having one instance. Though osm, an facilmap are the same story and I have a custom instance option in the settings for facilmap.

**Comment by vairag22** [comment]
> Yes, The only thing I don't like is it having one instance.

What 😕?

Didn't you reject adding redirects for Hackernews because it isn't a risk to user privacy, then we shifted the topic to a bug in Send redirects: [send.firefox.com](https://send.firefox.com) is not redirected to where it should instead it redirects to [mozilla.org](https://www.mozilla.org/en-US/) even though everything seems fine in the regex.

`const targets = [ /^https?:\/{2}send.invalid\/$/, /^ https ?: \/\/send\.firefox\.com\/$/, /^https?:\/{2}sendfiles\.online\/$/ ];`

You said you'll fix this and add new links to Send, if possible.

> Is this issue still relevant?

I meant, have you fixed the bug we discussed earlier?

**Comment by ManeraKai** [comment]
After seeing the source code of the homepage of hacker news, yes I won't add this frontend. This frontend (https://github.com/rajatkulkarni95/hckrnws) even states that it's for a better reading experience rather than a privacy this. And you are correct @vairag22, there's nothing wrong in the homepage of hacker news.
