### ISSUE TITLE
Can't make libredirect default search engine, "search" redirect doesn't work

### ISSUE THREAD

**Issue by Lippiece** [libredirect/browser_extension#362]
Illustration of the first problem:
![image](https://user-images.githubusercontent.com/47634624/175021711-2cb74ed2-8c09-4bd4-8ed2-d695f328617b.png)

The second:
1: ![chrome_1lgxXwg5fO](https://user-images.githubusercontent.com/47634624/175022123-c79e2b14-f188-4fba-bd81-586961d8066a.png)
2: ![chrome_DLJ8d4Th4w](https://user-images.githubusercontent.com/47634624/175022104-ffce7fe4-a045-49de-b62d-9f6aace0d55c.png)
3: ![chrome_xWa1bi03o4](https://user-images.githubusercontent.com/47634624/175022126-1c502c8e-b741-4159-8f36-973302adeae4.png)

**Comment by ManeraKai** [comment]
Use or bookmark the link https://search.libredirect.invalid/ to be able to use LibRedirect. Having it as a default search engine works perfectly in Firefox but not in chromium.
Even if I added redirections for https://google.com, the auto completion will still be run to google first and I can't intercept that traffic. I may re-add https://google.com in the code but you should also disable auto completion.

This problem is also happening with Qwant. I can't set it as my default search engine in chromium browsers.

**Comment by Lippiece** [comment]
@ManeraKai 

Thanks, I added https://search.libredirect.invalid/?q=%s as new search engine and it works fine.

> Even if I added redirections for https://google.com, the auto completion will still be run to google first and I can't intercept that traffic. I may re-add https://google.com in the code but you should also disable auto completion.

Redirection from google worked in version 17 or 19, can't remember.

Also, why are there no suggestions when using https://search.libredirect.invalid/?q=%s?

**Comment by ManeraKai** [comment]
I think I'll add

**Comment by a-kriya** [comment]
@ManeraKai On a related note, `search Regex` in this part of the [FAQs](https://libredirect.github.io/faq.html) is broken now:

><all_urls>: LibRedirect is dynamic and customizable. The targets e.g [youtube.com](https://youtube.com/), [twitter.com](https://twitter.com/) are written in [Regex](https://en.wikipedia.org/wiki/Regular_expression) and are much more complicated than to be hard-coded in the manifest. Ex: [search Regex](https://github.com/libredirect/libredirect/blob/master/src/assets/javascripts/helpers/search.js#L6=). Further more, we need to access the instances sites too to inject some localStorage variables.

**Comment by ManeraKai** [comment]
@a-kriya so late but fixed that.

**Comment by ManeraKai** [comment]
Well I don't think I can fix that problem :/ ofc search.libredirect.invalid is a domain that doesn't exist.

**Comment by bobajeff** [comment]
@ManeraKai I managed to get it to work by using it with the Redirector extension. I updated my comment with the details.

**Comment by HuckToohey** [comment]
I was following @bobajeff 's instruction but had not yet seen the comment about the additional redirect. That's what I was looking for. Thanks.

**Comment by ManeraKai** [comment]
We do have an owned url, libredirect.github.io. I can change the code so it also redirects from that if the url had a special path or query or something.

**Comment by ManeraKai** [comment]
See https://libredirect.github.io/docs.html#search_engine_firefox_android

**Comment by SevastianGit** [comment]
> > Also, why are there no suggestions when using https://search.libredirect.invalid/?q=%s?
> 
> I still didn't add this feature yet.

Hey, sorry to bump an old closed issue, maybe I should make a new one, just I saw you mention this here which is why I wanted to ask
Is this still planned to be added anytime soon? It's just unfortunately rather a dealbreaker compared to just using a single custom search engine in the browser settings. Due to how SearxNG instances can be (down occasionally), I wish to use LibRedirect as an automatic fallback solution in case one of the instances of my choice are down (I couldn't choose a "main instance" (that it'd prefer by default) and "fallback instance(s)" (that it'd go to in case the main instance is down), but I compromised by using two similar instances that it always randomly chooses inbetween. Maybe this needs a separate issue made). I could try Redirector, but I don't know if/think it has the ability to check if a website is down.
Thank you for your extension 🙏

**Comment by ManeraKai** [comment]
I did add it in this commit https://github.com/libredirect/browser_extension/commit/be9a72f3a2b0e9317e2229dca3006a27ec26dad3, does it not work?

**Comment by SevastianGit** [comment]
> I did add it in this commit [be9a72f](https://github.com/libredirect/browser_extension/commit/be9a72f3a2b0e9317e2229dca3006a27ec26dad3) and closed the issue, does it not work?

I'm on desktop, I chose two SearxNG instances that support suggestions while searching in the URL bar, the suggestions work when I use them usually, but when I choose LibRedirect as my search engine I get no search suggestions.

**Comment by ManeraKai** [comment]
Show me a screenshot of your LibRedirect settings.

**Comment by SevastianGit** [comment]
> Show me a screenshot of your LibRedirect settings.

Currently away from my PC, will send you as soon as I can (in some hours)👍
I also tried removing and re-adding the .invalid search engine manually (with the logic of how for example 4get tells you you have to re-add them if you change the autocomplete provider in their settings), but that didn't change anything.

**Comment by ManeraKai** [comment]
Oh you're talking about search suggestions, no we don't have them. The url gets converted when the user submits. Nothing happens before that. I don't know if this feature can be implemented though.
