### ISSUE TITLE
What is "Unsupported paths handling"?

### ISSUE THREAD

**Issue by mojo-jojo-7** [libredirect/browser_extension#648]
What does it do?

**Comment by ManeraKai** [comment]
We'll add an explanation for it, but basically if you have a "youtube.com/ads6dsa4a" link that is YouTube, but Invidious doesn't support it. So what should LR do? Should it "bypass" it so it can reach YouTube servers? or "block" the request so it won't reach YouTube for ofc privacy reasons.

**Comment by IkelAtomig** [comment]
> the default should be "Block" rather than "Bypass"

I totally agree with this.

**Comment by darlopvil** [comment]
> Opening https://github.com/libredirect/libredirect/issues page for example always showed me the Gothub "Error" (404) page regardless of that setting.

I was gonna post this. I think gothub doesn't support anything farther than the "homepage" of the project. The same happens with LibreMDB and the movie page. I can't see anything related to release dates, cast, connections, or anything else. It's all very summarized in a whole page.

**Comment by ManeraKai** [comment]
> I totally agree with this.

This will break things more than Ublock Origin even. It's not for newbie users, but the option is their.

**Comment by SethFalco** [comment]
> the default should be "Block" rather than "Bypass"

I actually disagree with this. It's important to think about the initial user experience. Users that haven't got through all the settings thoroughly may be inclined to think the extension is breaking their experience.

Things that yield a bad default user experience for clients should not be enabled by default. Meanwhile, those hardcore about privacy are expected to check the settings of what they install anyway.

**Comment by krystian3w** [comment]
> https://github.com/libredirect/browser_extension/issues/648#issuecomment-1457995175

Blocked Pop-ups skip strict block prompt if we use someting like:
```adb
||github.com^$all,from~=recommended-view-in-gothub-or-libremdb.*
```

Also cover option "open in new tab", so definitely need rewrite to minimum:
```adb
||github.com^$all,~popup,from~=recommended-view-in-gothub-or-libremdb.*
!
! or
!
||github.com^$doc,from~=recommended-view-in-gothub-or-libremdb.*
! AdGuard need "doc"/"document" to enable strict block prompt
```

**Comment by ManeraKai** [comment]
Alright, this issue has been for a long time and I will explain what I understood:
LibRedirect is not life Ublock Origin: the main thing that we focus on in LibRedirect is redirecting the "address bar", unlike uBlock Origin which blocks "background requests".
Ex: let's say I have a live youtube video and I want to watch it on CloudTube, now CloudTube does not support live chat, so I should in theory block any request wanting `youtube.com/live_chat`, but in practice, I won't even be redirected to youtube.com's website in the first place to have a background request wanting `youtube.com/live_chat`, I would be redirecting straight to a CloudTube instance.

LibRedirect only meets with uBlock Origin in iframes, so the "Unsupported paths handling" feature is in reality (in code) just for blocking iframes, I think it should be renamed from "unsupported paths" to "unsupported iframes" bc it's misleading. Also, the sites we redirect are main websites, they are not where you will fetch a JS tracking script from. So you won't see ex: `youtube.com/tracking_script.js`, but you will see `analytics.google.com/tracking_script.js`. So "Unsupported Paths handling" isn't a problem with LibRedirect, it was just added bc of iframes.

**Comment by SethFalco** [comment]
uBlock Origin does work actively on all requests actually, not just background ones!

It's primarily for background requests, but if you were to try and visit one of the blocked domains directly, it does indeed catch it and display a special uBlock Origin page.

![image](https://github.com/libredirect/browser_extension/assets/22801583/05e9274b-452a-4d69-8275-0a99d6ec6a73)

Here is what happens when I try to visit `analytics-sg.tiktok.com` directly. (There are real use-cases for this, like tracked links in emails that one might want to allow once or permanently.)

![image](https://github.com/libredirect/browser_extension/assets/22801583/21f66633-f4cc-40b8-a13b-0efeb106c617)

This is what people were asking for above! i.e. A page where it warns you that it can't be redirected, would you like to go to the original site, with a proceed button.

**Comment by ManeraKai** [comment]
> Here is what happens when I try to visit analytics-sg.tiktok.com directly. (There are real use-cases for this, like tracked links in emails that one might want to allow once or permanently.)

Those "address bar urls" are already supported by the frontends. Tell me a usecase that  happens with for example youtube.com that LibRedirect should block other than iframes.

> Is your explanation in https://github.com/libredirect/browser_extension/issues/648#issuecomment-1456384597 still valid, ManeraKai? If so, then SethFalco is right about what we're expecting from the feature.

No, my [latest explanation](https://github.com/libredirect/browser_extension/issues/648#issuecomment-1567993875) is my last thought. Let me say I didn't understand the theory and practice scenario till now.

**Comment by SethFalco** [comment]
Hmm, maybe I've misunderstood something here myself.

I thought the point of this feature was that unsupported paths would go to the actual site instead of the proxy.

i.e.

`https://www.youtube.com/premium` would not be proxied to Invidious because there is no Invidious page for it.

If that was never intended to be covered by this setting, then fair enough. I thought this was the very scenario the setting was meant to accommodate.
