### ISSUE TITLE
'Excluded from redirecting' Doesn't work.

### ISSUE THREAD

**Issue by amogusussy** [libredirect/browser_extension#665]
In the settings, I've set youtube.com (only the root URL) to not redirect, ([screenshot](https://imgur.com/KrxaXkx.png)) but when I open youtube.com, it still redirects to an invidious instance.

I only want it to redirect for youtube.com/watch URLs, and nothing else on the youtube.com domain. Is there a way to do this, or fix this bug?

**Comment by ManeraKai** [comment]
The thing is Exclude from redirecting is taking everything "literally". What I understood was happening was that you normal (without LibRedirect), when you type `youtube.com`, you go to `http://youtube.com` and then you get redirects to https so `https://youtube.com`, but LibRedirect intercepts the first one (`http://youtube.com`) and recognize it as not in the excluded list, so it redirects it xD.
I (as an advanced user) prefer the Regex way:
![image](https://github.com/libredirect/browser_extension/assets/40805353/6cfb70fd-b055-403b-8ba1-f5baa9df7a6c)
`https?:\/\/youtube\.com\/?$`
The problem is I can't know if the user is literally meaning to just not redirect the https version, or he is meaning both http and https.
I will though make a change to ignore `http` and `https` and let's see if one disagrees in the future.

**Comment by ManeraKai** [comment]
Alright, till the next release comes out, you can use the Regex: `https?:\/\/youtube\.com\/?$`.

**Comment by ManeraKai** [comment]
@Elaborendum is this still the same in v2.8?

**Comment by ManeraKai** [comment]
Try to add `https://youtubeembedcode.com/en/` to your exceptions rather than just `https://youtubeembedcode.com/`.

**Comment by ManeraKai** [comment]
Yes you should change most to regex. I can't predict what the user wants exactly that's why.
