### ISSUE TITLE
Update requests unnecessary permissions to read and write bookmarks

### ISSUE THREAD

**Issue by foerster-rwth** [libredirect/browser_extension#688]
Last week I opened up the issue that the libredirect update recently has wanted permissions that it neither needs nor is going to get from conscientious users (see https://github.com/libredirect/browser_extension/issues/685). 

Which means that I have to decline the installation of the update every day anew. This is a questionable behaviour of the update, and it is tiring as well.

The issue #685 was answered by "ManeraKai" -- in an unsatisfactory fashion -- and then marked as "completed".

It is not completed. The issue persists, and I would like to know what the matter is with this.

I am certainly not the only user who does not want to give permissions to read and write bookmarks to a plug-in that claims to improve privacy.

A clarification will be appreciated.

**Comment by ManeraKai** [comment]
https://github.com/libredirect/browser_extension/issues/685#issuecomment-1532007286

**Comment by ManeraKai** [comment]
ok I'm able to make "bookmarks" optional, but I'm not able to make "contextMenus" to be so.

For "contextMenus" to be optional, I should be using [.overrideContext](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/overrideContext) instead of [.create](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create), which will override the whole context menu (which will make someone assassinate me).

**Comment by acidghost** [comment]
Will permission to read bookmarks be optional in the next release?

**Comment by ManeraKai** [comment]
Yes

**Comment by acidghost** [comment]
Great, thanks!
