### ISSUE TITLE
Some embedded YT videos do not work

### ISSUE THREAD

**Issue by Moonstone3010** [libredirect/browser_extension#689]
Some types of embedding (incorrect I think) make the frame non-clickable.

Video embedded in iframe in format:
https://www.youtube.com/embed/XxXXXXXxX
works with LibRedirect

Video embedded without iframe in format:
https://youtu.be/XxXXXXXxX
displays a locked video with a play button that does not work.
However, after disabling LibRedirect the youtube video can be played.

**Comment by ManeraKai** [comment]
Is this for a specific website? Show me a real example bc it there are a ton of different causes for this to happen.

**Comment by Moonstone3010** [comment]
The page where I found the problematic links is quite complicated and requires a login. There is no direct link, it is part of a course. I can describe what you need to do one by one - if you want to, but you probably don't.

**Comment by ManeraKai** [comment]
I see.
I inspected the code, there's nothing that should cause this problem. I can assume it's bc of your "complicated course website". Those "complicated websites" don't embed in the normal way, they add something on top you (additional layer you can say), that's why if you had a different data response to that embed, it will break. I experienced this before with twitter embeds I believe.

Embeds are in general a headache:
1. The main website won't accept instances responses bc of [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)
2. Embeds break bc of a top layer on top on them (your case mostly)
3. Instances themselves aren't configured to allow to be embedded
4. They fingerprint LibRedirect. That's why we disabled them by default.

So yeah... I think I'm gonna close the issue. I really don't have a solution for it nor for the other issues about embeds.
