### ISSUE TITLE
Extension shortcut/keybind to remove the current instance from the list

### ISSUE THREAD

**Issue by candlew1ck** [libredirect/browser_extension#725]
When I have a lot of instances enabled, sometimes one of the instances I added will have a garish custom stylesheet or broken functionality. It's a pain to manually enter the settings menu, find the offending instance in a list of possibly dozens of instances, and click 'delete' for every single broken instance. It would be nice to have a keyboard shortcut that automatically deletes the current instance from the list of instances and subsequently redirect to a random one (otherwise the switch instances shortcut will not work.)

**Comment by candlew1ck** [comment]
I'm entirely certain most people would rather maintain a list of reliable instances than maintain their own private instances for every service they want to use. Transitioning to this new system unsolves the problem of users wanting an easy way to consume content without downloading 400mb of ads and trackers, and creates a new problem where users will need to water-cool their 2012 Thinkpad T420's because they need to run 15 different web services 24/7, as well as figure out how to route each one through Lokinet. Plus, most users don't have 2GB of ram to spare, so self-hosting a heavy service like Invidious will be impossible for most people. If people don't want to use Youtube's official website (which has recently started forcing users to turn off their ad blockers to watch videos) they will have to use a public Invidious instance, and then they'll want a way to auto-redirect to it... and we're back where we started. People will still depend on the browser extension, so refusing to add features for that usecase, the original core usecase which was the sole purpose of both LibRedirect and Privacy Redirect and the reason why anybody installed either of those extensions, is a big "F you" to the users.

Good luck getting privacy novices to switch to libre frontends when the only browser extension that actually makes this easy by supporting tons of services and auto-fetching lists of instances abandons said functionality because the maintainer doesn't want to "add bandages." A bandage is often better than a full-body skin graft.

**Comment by ManeraKai** [comment]
> and creates a new problem where users will need to water-cool their 2012 Thinkpad T420's because they need to run 15 different web services 24/7

Users will only run the frontends binaries they use, so they won't be 15 unless they are really advanced web surfers.

> Plus, most users don't have 2GB of ram to spare, so self-hosting a heavy service like Invidious will be impossible for most people.

Actually running a binary for a frontend doesn't consume that much ram especially if you are just one user. I did a benchmark a while ago and posted the results in our matrix room:
![image](https://github.com/libredirect/browser_extension/assets/40805353/257a98d7-69d2-466c-baef-21cd13a1047a)
> This is the total memory usage while using LibReddit, Rimgo, AnonymousOverflow, SimplyTranslate, Dumb through LibRedirect Frontends Manager. I browsed each one of them sequentially bc I'm just one user on the computer, and the results are pretty good

Here it's using at maximum ~170 MB of ram while running all those frontends. So that's really nice, but... other frontends are using Node.js or PHP or other languages and I needed to wrap them with docker. Here are the results for "frontends running in docker":
![image](https://github.com/libredirect/browser_extension/assets/40805353/e349e0ad-c66a-4a49-a956-6b1019769947)
I still didn't test invidious out (I'm having troubles in running it locally), but SearXNG is the worst case here.

So the solution to those high memory consumption frontends? Having a public instances list?? No! Running invidious for people is really costly, that's why [pussthechat](https://pussthecat.org/invidious/) stopped doing that for free. And there are other problems than just cost: https://github.com/libredirect/browser_extension/issues/663#issue-1627865230. The real solution is to make frontends lighter so anyone can host them locally.

> as well as figure out how to route each one through Lokinet

No they just run Lokinet and it acts like a VPN.

I'm just doing my piece, redirecting is our main scope, Frontends Manager will be in our scope too, but the problem of "Anonymizing your IP address" is already a huge problem by itself and should be the scope of other projects like Lokinet.

**Comment by candlew1ck** [comment]
The benchmarks are a welcome surprise. I guess I'm happy to be proved wrong about the difficulty of self hosting privacy software because it means more decentralization. I think the point that privacy novices would rather keep a list of decent instances than mess with self hosting still stands until the latter is proven to be nearly as convenient as the former with minimal hassle getting each service set up.

> So the solution to those high memory consumption frontends? Having a public instances list??

When it comes to Invidious, I have 3 options:

1. Use youtube dot com
2. Use a public instance(s)
3. Self-host

1 is off the table for obvious reasons. I don't have 2g of ram to spare, so 3 is currently unachievable for me (and probably most people). I could use some old computer and host Invidious on the network, but that's an extra attack vector and, by your own admission, is a pain in the ass to set up. Most normal people aren't going to set that up anyway. Therefore, 2 is the only feasible option for myself and the vast majority of privacy novices. So the answer to your rhetorical question is yes.

> Bruh xD, running invidious for the public is also really costly, that's why [pussthechat](https://pussthecat.org/invidious/) stopped doing that for free.

I count 27 public instances on https://docs.invidious.io/instances/. One person switching their instance to a paid system does not prove that Invidious is too costly to feasibly run a public instance. 

> I'm just doing my piece, redirecting is our main scope,

If redirecting to public instances of free frontends is still within your main scope, then I don't see a reason to close issues relating to that functionality just because they're "not planned." I totally understand the urge to achieve Inbox 0, but you're just making it harder for possible contributors to actually find out about issues with the extension. Then again I have never maintained a project at this scale and as long as you wouldn't immediately defecate on someone's pull request to implement this because it's not planned then I can't really complain.

**Comment by ManeraKai** [comment]
> One person switching their instance to a paid system does not prove that Invidious is too costly to feasibly run a public instance

You will be hopping between 27 instances, constantly switching from a broken one and being forced to migrate all your subscription and settings, not convenient, nor trust-worthy. The practical solution is to make invidious lighter or designed for one user to be hosted locally, just how [FreeTube](https://github.com/FreeTubeApp/FreeTube) works without using 2GB of ram as a concept.

> I totally understand the urge to achieve Inbox 0, but you're just making it harder for possible contributors to actually find out about issues with the extension. Then again I have never maintained a project at this scale and as long as you wouldn't immediately defecate on someone's pull request to implement this because it's not planned then I can't really complain.

Well after 680+ issues on github and codeberg... you start having a disorder to CLOSE EVERY ISSUE BC THEY KEEP APPEARING xD

LibRedirect has a history, after we forked from Privacy Redirect, we started implementing features to manage multiple instances, some of them are Unify Settings, Auto Switch Instance, Ping Instances, Update-able Instances List. Over time you will realize all those features buggy and and built on top of a fundamentally wrong idea (trust my website instead of youtube.com). So we started removing all those features, and now we're focusing on Frontends Manager and I really encourage frontend developers to make their frontends lighter for local hosting. A PR for e.g Unify Settings or Auto Switch Instance won't be accepted.

**Comment by candlew1ck** [comment]
>  constantly switching from a broken one and being forced to migrate all your subscription and settings

I never store subscriptions or settings on instances, except for purely cosmetic changes like switching to dark theme. The real solution is to store the important data locally, like using an RSS feed reader to manage channel subscriptions. Anyway, you're painting an extremely skewed strawman of what it's like to use public instances that I want to chalk up to a conflict of interest with Frontends Manager.

> you will realize all those features are buggy and and built on top of a fundamentally wrong idea (trust my website instead of youtube.com)

Yes, I will always trust a random internet blogger's Invidious instance over Youtube's official site. If you reject this as a "fundamentally wrong idea," why isn't this repository archived or explicitly discontinued?

If your ultimate plan is to stop maintaining LR in favor of Frontends Manager, *explicitly state that and archive this repository immediately* so that a fork can be made that focuses on the original usecase and refrains from immediately shooting down quality of life improvements relating to said usecase because they aren't planned. Otherwise, you're sentencing LR to a slow, painful death.

**Comment by ManeraKai** [comment]
The extension is for redirecting, and Frontends Manager is for hosting the frontends locally. So they both work hand in hand.

Btw Freetube does store things locally, if it just had an option to "open in browser" instead of opening in a separate window. I'll ask them they're already using Electron so.

Also, I'm not saying to use YouTube's site directly, as I said before I quote:
> I'm just doing my piece, redirecting is our main scope, Frontends Manager will be in our scope too, but the problem of "Anonymizing your IP address" is already a huge problem by itself and should be the scope of other projects like Lokinet.
