### ISSUE TITLE
[Feature Request] Automatic Setup and Improved User Experience

### ISSUE THREAD

**Issue by 8ullyMaguire** [libredirect/browser_extension#920]
I wish I could recommend the libredirect browser extension to more people, but for that to happen, it needs to provide a more user-friendly experience out of the box. The current setup process and the need for manual configuration can be a barrier for some users. To make libredirect more accessible and widely adoptable, I would like to suggest the following improvements:

### 1. Enable Redirection by Default
By default, the extension should have redirection enabled for all supported services. This would provide users with the benefits of libredirect immediately, without the need for them to navigate through complex settings or enable each service individually.

### 2. Automatic Instance Selection
The extension should automatically select the best-performing instances for each service, based on factors such as ping time. This would ensure that users always have a smooth and reliable experience, without the need to manually choose instances.

### 3. Sync Configuration Across Instances
Automatically export/import configuration across instances to ensure a consistent experience.

**Comment by NoPlagiarism** [comment]
### 1. Almost no one enables all of redirections

First of all. Users should choose themselves what alternative frontend to use. Do I even need to remind that YouTube has about 10 alternative frontends?

Secondly, not all users wanna use redirections for all services:

- If you are contributor on Genius, you don't want to be redirected to [Dumb](https://github.com/rramiachraf/dumb)
- If you want to upload image on Imgur, you go to Imgur, not to [rimgo](https://codeberg.org/rimgo/rimgo)

And finally. Let's find some services, which are.. Let's say, they have specific audience and use cases. It's not that they are useless, I use one of them sometimes and will use it. Just.. Not  for normal users

- [Wayback Classic](https://github.com/ticky/wayback-classic) is Wayback Machine alternative frontend and it's main goal is... Old browsers. Yeah, just that. If you have modern browser, you don't need it.
- [Wikiless](https://github.com/Metastem/wikiless) is, obvi, Wikikpedia alternative frontend. It has just 2 reasons to exist: circumvent censorship and  preventing Wikipedia getting your IP address. If you have no Wikipedia censorship problems in your country and you trust Wikipedia, you don't need it

I think installation could be simplified, but not by this

### 2. Ok, but

Prettifying and simplifying instances could be nice, but how exactly browser extension can get server load of specific instance? For example, [farside](https://github.com/benbusby/farside) can do sth like that, because it's hosted gateway that redistributes redirections between users

### 3. Close to impossible

1. I don't think all frontends will support this ever
2. So.. LibRedirect should somehow extract settings from one instance, then somehow export it to other. Then compare it on every load to do it automatically.... I'm not close to main contributor and I'm not developer, but I don't think this very-hard-to-implement feature is needed in project named Lib***Redirect***

**Comment by ManeraKai** [comment]
> 3. Sync Configuration Across Instances

This was implemented by us before. We called it Unify Settings, but it had a ton of problems: [whitepaper.md](https://github.com/libredirect/frontends_manager/blob/main/whitepaper.md)

**Comment by IkelAtomig** [comment]
All of this are like, we need to create the extension to a saturation point, which will be like greet the user. 

If the user wants everything automated, we set it up for them. If not, we make them to choose everything.

**Comment by ManeraKai** [comment]
> 2. Automatic Instance Selection

The extension should automatically select the best-performing instances for each service, based on factors such as ping time. This would ensure that users always have a smooth and reliable experience, without the need to manually choose instances.

I added this https://github.com/libredirect/browser_extension/commit/dd4b741e4ab7d6892cbc4a4316c73d92ef48efed
I will improve on it with making some popups if there were no selected frontends, and if the selected instance is offline.

**Comment by ManeraKai** [comment]
https://github.com/libredirect/browser_extension/commit/1492345b0d2f0f4d6d4a7a6f8814596785a472b0

**Comment by ManeraKai** [comment]
YouTube is now enabled by default. Only YouTube. The only request I won't be able to make is synchronizing between frontends.
