### ISSUE TITLE
[Bug] Unrecognized manifest key 'browser_specific_settings'.

### ISSUE THREAD

**Issue by 825i** [libredirect/browser_extension#921]
![Screenshot 2024-05-07 092802](https://github.com/libredirect/browser_extension/assets/58630825/90b90d36-12cf-4636-8169-75a88ebbd460)

Extension Version: 2.8.4
Browser: Brave Browser 1.65.126
OS: Windows 11

Code block:

```
"browser_specific_settings": {
		"gecko": {
			"id": "7esoorv3@alefvanoon.anonaddy.me",
			"strict_min_version": "89.0"
		},
		"gecko_android": {
			"strict_min_version": "113.0"
		}
	},
```

**Comment by IkelAtomig** [comment]
It was meant to determine minimum browser version for the extension to run on Firefox based browsers. This errors pops out only during developer mode in chrome.

It doesn't affect anything in Chromium based browser. It just shows because the key is not defined in their manifest documentation of Chromium and only meant for firefox. Nothing much

Regarding chrome Web Store : http://libredirect.github.io/faq.html#chrome_web_store
