### ISSUE TITLE
Add Yacy

### ISSUE THREAD

**Issue by ThunderHen** [libredirect/browser_extension#923]
Code https://github.com/yacy/yacy_search_server
Install https://yacy.net/download_installation/
Main website yacy.net
Instances https://yacy.searchlab.eu
https://search.lomig.me
https://yacy.ecosys.eu
https://search.webproject.link
Instances list at https://search.webproject.link/Network.html?page=2&maxCount=1000 go to any instance  and use the path /Network.html?page=2&maxCount=1000

**Comment by ManeraKai** [comment]
It's not a frontend. Yacy promotes to host your own instance to help the P2P network rather than using other people's instances. I can't add all those instances. They have no proper domain names because, they are peers not instances.
If you want to add it as a search engine, right click the address bar:
![image](https://github.com/libredirect/browser_extension/assets/40805353/c9b6b96d-61c3-4356-b08b-205bf4b34f3e)
