### ISSUE TITLE
Add Shoelace

### ISSUE THREAD

**Issue by otoayana** [libredirect/browser_extension#932]
Code: https://git.sr.ht/~nixgoat/shoelace
Instance: https://shoelace.mint.lgbt/
Instance List: https://git.sr.ht/~nixgoat/shoelace-docs/tree/master/docs/instances.md
For: https://threads.net

This is a rather new project of mine, and might make a good fit for the plugin. Would need a new section for Threads, since this is one of the first, if not the first, alternative frontends for Threads.

**Comment by nixgoat** [comment]
Instance list has been added, although not yet provided in a JSON format.

**Comment by IkelAtomig** [comment]
It is great project. I highly appreciate it.

But are you sure about this. Because threads is gonna be into the fediverse. If so, people would view the posts from there, which would make the project redundant.

And Threads, since a project of meta, will rate limit instances.

**Comment by nixgoat** [comment]
I am sure. Meta has put a lot of ties with federation. I explained this in [Lemmy](https://slrpnk.net/comment/8941056), but essentially, any instance that federates with Threads has to comply with their privacy policy. As quoted from the [official help page](https://help.instagram.com/515230437301944?helpref=faq_content):

> Your server will share information with Threads, for example, if you like content from Threads users that's been shared to your server. You can learn more about how we process your data in our [Threads Supplemental Privacy Policy](https://help.instagram.com/515230437301944?helpref=faq_content).

Additionally, not all Fediverse instances federate with Threads, due to how Meta has previously handled their user's data. Not to mention, this adds another layer of vulnerability in the form of needing another login to access content from Threads using a Fediverse instance.

Federation is also currently region-locked to the US, Canada, and Japan, which means any account owned by someone outside of those jurisdictions is inaccessible from the Fediverse. It's also presented as an option for Threads users, instead of a de facto structure of the network. Lastly, while this also applies to Shoelace, any private accounts are inaccessible from the Fediverse, requiring a Threads account to be usable.

TL;DR: Threads on the Fediverse is still privacy-invasive, and it's support is incomplete

**Comment by IkelAtomig** [comment]
Alright then, this answer me well. This is in.

**Comment by ManeraKai** [comment]
How to redirect it's links?

**Comment by otoayana** [comment]
> How to redirect it's links?

Here's a breakdown for each supported route

## Posts
All of the following Threads routes should redirect to an instance's `/t/[id]` route:

- `/@[username]/post/[id]`
- `/post/[id]`
- `/t/[id]`

Replies don't have their own route, since they're also declared as posts.

## Users
Route is `/@[username]` for both Threads and Shoelace.
