### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by tEctutoRIt** [libredirect/browser_extension#961]
I like your extension, but this new update has made it really difficult to change settings and involves a lot of scrolling. It was much easier to see which services were active earlier; now it's impossible without going into the menu bar of each item, and it involves a lot of repetitive tasks.

**Comment by ManeraKai** [comment]
The Old UI was written in Vanilla JS. It was unmaintainable. The sidebar was going to explode at any minute. I can think of a way to show the enabled instances in the new UI.

**Comment by IkelAtomig** [comment]
@tEctutoRIt - There is an idea, how about you just scroll over the service, so you don't need to repetitively click ?

**Comment by ManeraKai** [comment]
Now I need to make it transparent or something...

https://github.com/user-attachments/assets/297301dc-05b9-4e72-b639-866b1307e589

**Comment by tobika** [comment]
I came to this issue because I couldn't figure out that you have to click on service and a list popup opens up.
Maybe you could add an down arrow to make it clear for the user that this is a list.

**Comment by ManeraKai** [comment]
This hovering is giving a lot of errors, there needs to be other solution like the popup in the settings page.

**Comment by ManeraKai** [comment]
I meant explode in the sense that we have over 40 services in a sidebar that is not searchable and is always expanding. I rewrote the UI in Svelte in prder to simplify the code, in order to add more complex UI components easily. I didn't close this issue because I want to find a solution to it.

**Comment by AlexBlandin** [comment]
Yes, having 40 services in the sidebar is not "searchable", but neither is scrolling the Service list (arguably, the limited window makes it harder to see 'at a glance' if something is available). While the Service list's text box is searchable, sadly it's not obvious that you **can**, since the caret can easily disappear behind the logo of whichever service is default (e.g. youtube), so I hadn't even realised you could type in it for a while...

![Caret is easily overlooked in Service list](https://github.com/user-attachments/assets/c77f55fc-fa95-4834-b74d-eacc71862e9f)

Meanwhile, all this is compounded by not knowing **where** to look, i.e. that we need to go to General (2) → Service. This discoverability especially hurts as the links to configure in the pop-up are stale (there's no page for each service now). Having two "General" tabs doesn't read correctly, plus configuring each service seems like something that should be the default and at the top, which would mean there's more of a chance that someone realises "Oh, this is where we change instances" vs. thinking it's some spill-over or secondary General Settings tab, as the name implies.

![Two General tabs, and the 'wrong' one is the default for changing redirects](https://github.com/user-attachments/assets/00e2ff9c-3777-4c3a-a1b5-1749658757b3)

So, for immediate and quick things that would improve the UI:
1. Rename the "General" (service) tab to something like "Redirect", and maybe have it as the default settings tab?
2. Improve the Service selection in simple ways, shift the logo/name across to the right just a little more (so the caret is easier to see), definitely clearer indication it's a text box and thus searchable (plenty of space to just say "Type to search", etc, and it's using the same design language as other non-searchable / not-text-input lists, so some visual distinguishing would be useful), and perhaps a larger window to scroll in, 
3. A little more work, but something that's really just needed in some capacity as it's otherwise breaking existing functionality, is having the popup menu's links back to the settings work (e.g. `chrome-extension://oladmjdebphlnjjcnomfhhbfdldiimaf/https://github.com`); though I can appreciate that changing the framework means this is going to probably require some shift in process.

![Clickable link in popup doesn't resolve to page](https://github.com/user-attachments/assets/fdb19a30-b744-4490-a9cb-2e16137e68a2)

I feel this really is pertinent given that 2.9 is, according to the settings import/export, at least partially incompatible with 2.8's settings.

There are nice-to-haves, like ways of putting things on the sidebar that are relevant (perhaps filtered to only the enabled services/redirects), but those are things that need to come after the fundamentals, such as ensuring people can change their settings (so config link in popup really should work), know where they can change their settings (not having two "General" tabs)... and know that they need to change their settings (some way to communicate that the update is (partially) incompatible with previous settings, perhaps offering to at least save a backup so they can recreate them, but that's a stretch goal).

As an aside/addendum, I'd definitely want to think about how long, on-page lists is already the UI/visual language of libredirect, namely via the instance lists! I imagine improving those would be a significant amount of not necessary work, though. Still, having something similar (40 services) in the sidebar wasn't incongruent with libredirect, at least in principle.

However, if we're wanting improvements in searchability, readability, and discoverability, then perhaps the Service list already demonstrates _exactly_ what we needed, but that it should go **in the sidebar itself**, then just redirecting to the specific page for each service like before; would give the popup simple pages to link to again. I'm not certain what the situation is with the framework, as frontend isn't my domain, but that does feel like a tidy way to resolve almost all of the above issues in one go! Perhaps this does mean a move back towards separate pages like before, which may have been something you were forced into on technical grounds, but I wouldn't know. Still, that would probably be a non-trivial amount of work, hence why this is an addendum, as there's much simpler little changes that would also help (and are not necessarily incompatible with this) which I wanted to outline above.

**Comment by ManeraKai** [comment]
The two General tabs was a typo. It's fixed now in the source code.

**Comment by ManeraKai** [comment]
This should now solve the "disable hint" problem

https://github.com/user-attachments/assets/1333b788-a1ac-473f-bea1-ecd1acf8ca28

**Comment by ManeraKai** [comment]
Settings near each Service in the popup:

https://github.com/user-attachments/assets/6f2c234c-b09b-493f-87cc-3771b8821900

**Comment by ManeraKai** [comment]
Indicating that the dropdown is searchable:

https://github.com/user-attachments/assets/4c28f895-f1e1-41b3-a93d-4388ba2d3e53

**Comment by ManeraKai** [comment]
I don't want to add the service list  to the sidebar. It will be inconsistent with the UI. The settings button right to each service in the popup should be enough to not make service options too deep.

**Comment by IkelAtomig** [comment]
This is a great idea than the Magnifying glass.


Aug 18, 2024, by ***@***.***:

**Comment by ManeraKai** [comment]
Rewrote the version updating process, and allowed importing from previous versions. Hopefully it won't cause any problems.

**Comment by IkelAtomig** [comment]
Upto how may versions does it support in backwards previously it was one or two.

And this is some great improvements for v3.0. Should have refined things further before releasing v2.9 and gave a thought or brainstorming regarding usability.
18 Aug 2024, by ***@***.***:

**Comment by ManeraKai** [comment]
It's ok. We can release after some days.
